version: "3.7"
services:
  install:
    build:
      dockerfile: install.Dockerfile
      context: .
    depends_on:
      - mysqld
    environment:
      MYSQL_DATABASE: rpgpal_padb
      MYSQL_HOST: mysqld
      MYSQL_PASSWORD: 22SilentUlnaes #${MYSQL_PASSWORD}
      MYSQL_USER: rpgpal_pa
    volumes:
      - "./html/:/var/www/html/"
  apache:
    build:
      dockerfile: apache.Dockerfile
      context: .
    environment:
      MYSQL_DATABASE: rpgpal_padb
      MYSQL_HOST: mysqld
      MYSQL_PASSWORD: 22SilentUlnaes #${MYSQL_PASSWORD}
      MYSQL_USER: rpgpal_pa
    restart: always
    ports:
      - "8080:80"
    volumes:
      - "./html/:/var/www/html/"
  mysqld:
    image: mariadb:10
    environment:
      MYSQL_DATABASE: rpgpal_padb
      MYSQL_PASSWORD: 22SilentUlnaes #${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: 22SilentUlnaes #${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: rpgpal_pa
    restart: always
    # volumes:
    #   - mysql-data:/var/lib/mysql
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:5
  #   environment:
  #     PMA_HOST: mysqld
  #     PMA_PASSWORD: 22SilentUlnaes #${MYSQL_ROOT_PASSWORD}
  #     PMA_USER: root
  #   ports:
  #     - "5000:80"
  #   restart: always
# volumes:
#   mysql-data:
